package models;
// Generated 14/04/2018 10:56:26 AM by Hibernate Tools 4.3.1



/**
 * Encargado generated by hbm2java
 */
public class Encargado  implements java.io.Serializable {


     private String cedula;
     private String nombre;
     private String apellido;
     private String celular;
     private String correo;
     private String cargo;
     private String sede;
     private String facultad;
     private String programa;

    public Encargado() {
    }

	
    public Encargado(String cedula, String nombre, String apellido, String celular, String correo, String cargo, String facultad, String programa) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.apellido = apellido;
        this.celular = celular;
        this.correo = correo;
        this.cargo = cargo;
        this.facultad = facultad;
        this.programa = programa;
    }
    public Encargado(String cedula, String nombre, String apellido, String celular, String correo, String cargo, String sede, String facultad, String programa) {
       this.cedula = cedula;
       this.nombre = nombre;
       this.apellido = apellido;
       this.celular = celular;
       this.correo = correo;
       this.cargo = cargo;
       this.sede = sede;
       this.facultad = facultad;
       this.programa = programa;
    }
   
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getSede() {
        return this.sede;
    }
    
    public void setSede(String sede) {
        this.sede = sede;
    }
    public String getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(String facultad) {
        this.facultad = facultad;
    }
    public String getPrograma() {
        return this.programa;
    }
    
    public void setPrograma(String programa) {
        this.programa = programa;
    }




}


